import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

// Node built-ins, both bare ("fs") and prefixed ("node:fs") — kept external so
// esbuild doesn't try to bundle them into the desktop plugin.
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // NOTE: @viz-js/viz (the Graphviz WASM engine behind the dependency-graph
  // tab) embeds its .wasm inside its own JS bundle, so it must stay INTERNAL —
  // bundling it is what makes the graph work with no network call, which
  // Obsidian's CSP requires.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
